#!/bin/bash
  # Copying files

ROOT_UID=0
DEST_DIR=

# Destination directory
if [ "$UID" -eq "$ROOT_UID" ]; then
  DEST_DIR="/usr/share/themes"
else
  DEST_DIR="$HOME/.themes"
fi

repodir=$(cd $(dirname $0) && pwd)
srcdir=${repodir}/src

  rm -rf $DEST_DIR/Matcha*

# Copying files
	echo -e "   Installing Matcha ..."

	themedir=$DEST_DIR/Matcha
	install -d ${themedir}

	# Install index.theme
	cd ${srcdir}
	cp -ur \
	index.theme \
	${themedir}/index.theme

	# Install GNOME Shell Theme
	install -d ${themedir}/gnome-shell
	cd ${srcdir}/gnome-shell
	cp -ur \
	extensions \
	no-events.svg \
	no-notifications.svg \
	process-working.svg \
	${themedir}/gnome-shell

	cp -ur \
		assets \
		${themedir}/gnome-shell/assets

	cp -ur \
		gnome-shell.css \
		${themedir}/gnome-shell/gnome-shell.css

		glib-compile-resources \
		--sourcedir=${themedir}/gnome-shell \
		--target=${themedir}/gnome-shell/gnome-shell-theme.gresource \
		gnome-shell-theme.gresource.xml

	# Install GTK+ 2 Theme
	install -d ${themedir}/gtk-2.0
	cd ${srcdir}/gtk-2.0

	cp -ur \
		gtkrc \
		assets \
		apps.rc \
		main.rc \
		panel.rc \
		xfce-notify.rc \
		menubar-toolbar \
		${themedir}/gtk-2.0


	# Install GTK+ 3 Theme
	install -d ${themedir}/gtk-3.0
	cd ${srcdir}/gtk-3.0
	cp -ur \
		assets \
		gtk.css \
		gtk-dark.css \
		${themedir}/gtk-3.0


	# Install Metacity Theme
	install -d ${themedir}/metacity-1
	cd ${srcdir}/metacity-1
	cp -ur \
		*.svg \
		metacity-theme${color}-1.xml \
		metacity-theme${color}-2.xml \
		metacity-theme${color}-3.xml \
		${themedir}/metacity-1

# Set Matcha Gtk Themes
  echo "Setting the theme..."
  gsettings set org.gnome.desktop.interface gtk-theme Matcha
  gsettings set org.gnome.desktop.wm.preferences theme Matcha
  echo "Done!"


