#!/bin/bash
  # Copying files

ROOT_UID=0
DEST_DIR=

# Destination directory
if [ "$UID" -eq "$ROOT_UID" ]; then
  DEST_DIR="/usr/share/themes"
else
  DEST_DIR="$HOME/.themes"
fi

repodir=$(cd $(dirname $0) && pwd)
srcdir=${repodir}/src

  rm -rf $DEST_DIR/Matcha*

# Copying files
for color in '' '-dark'; do
	echo -e "   Installing Matcha${color} ..."

	themedir=$DEST_DIR/Matcha${color}
	install -d ${themedir}

	# Install index.theme
	cd ${srcdir}
	cp -ur \
	index.theme \
	${themedir}/index.theme

	# Install GNOME Shell Theme
	install -d ${themedir}/gnome-shell
	cd ${srcdir}/gnome-shell
	cp -ur \
		assets \
		extensions \
		process-working.svg \
		${themedir}/gnome-shell

	cp -ur \
		no-events${color}.svg \
		${themedir}/gnome-shell/no-events.svg

	cp -ur \
		no-notifications${color}.svg \
		${themedir}/gnome-shell/no-notifications.svg

	cp -ur \
		calendar-arrow-left${color}.svg \
		${themedir}/gnome-shell/assets/calendar-arrow-left.svg

	cp -ur \
		calendar-arrow-right${color}.svg \
		${themedir}/gnome-shell/assets/calendar-arrow-right.svg

	cp -ur \
		gnome-shell${color}.css \
		${themedir}/gnome-shell/gnome-shell.css

		glib-compile-resources \
		--sourcedir=${themedir}/gnome-shell \
		--target=${themedir}/gnome-shell/gnome-shell-theme.gresource \
		gnome-shell-theme.gresource.xml

	# Install GTK+ 2 Theme
	install -d ${themedir}/gtk-2.0
	cd ${srcdir}/gtk-2.0
	cp -ur \
		apps.rc \
		main.rc \
		panel.rc \
		xfce-notify.rc \
		menubar-toolbar \
		${themedir}/gtk-2.0

	cp -ur \
		gtkrc${color} \
		${themedir}/gtk-2.0/gtkrc

	cp -ur \
		assets${color} \
		${themedir}/gtk-2.0/assets

	cp -ur \
		menubar-toolbar${color}.rc \
		${themedir}/gtk-2.0/menubar-toolbar/menubar-toolbar.rc 

	# Install GTK+ 3 Theme
	install -d ${themedir}/gtk-3.0
	cd ${srcdir}/gtk-3.0
	cp -ur \
		assets \
		gtk-dark.css \
		${themedir}/gtk-3.0

	cp -ur \
		gtk${color}.css \
		${themedir}/gtk-3.0/gtk.css

	cp -ur \
		thumbnail${color}.png \
		${themedir}/gtk-3.0/thumbnail.png

	# Install Metacity Theme
	install -d ${themedir}/metacity-1
	cd ${srcdir}
	cp -ur \
		metacity-1 \
		${themedir}

	# Install xfwm4 Theme
	install -d ${themedir}/xfwm4
	cd ${srcdir}/xfwm4
	cp -ur \
		assets/*.png \
		themerc \
		${themedir}/xfwm4

	# Install CINNAMON Theme
	install -d ${themedir}/cinnamon
	cd ${srcdir}/cinnamon
	cp -ur \
		common-assets \
		${themedir}/cinnamon

	cp -ur \
		assets${color} \
		${themedir}/cinnamon/assets

	cp -ur \
		cinnamon${color}.css \
		${themedir}/cinnamon/cinnamon.css

	cp -ur \
		thumbnail${color}.png \
		${themedir}/cinnamon/thumbnail.png

	# Install openbox Theme
	install -d ${themedir}/openbox-3
	cd ${srcdir}
	cp -ur \
		openbox-3 \
		${themedir}

	# Install Unity Theme
	install -d ${themedir}/unity
	cd ${srcdir}
	cp -ur \
		unity \
		${themedir}

done

